name: dailysheetblp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependency_overrides:
  collection: ^1.14.12

dependencies:
  flutter:
    sdk: flutter

  gradient_app_bar: ^0.1.3
  flutter_slidable: "^0.5.3"
  google_fonts: ^0.3.10
  cloud_firestore: ^0.13.2+1
  mailer: ^3.0.4
  flutter_datetime_picker: ^1.3.5
  expandable: ^4.1.3
  flutter_statusbar_text_color: ^0.1.2
  charts_flutter: ^0.9.0
  shared_preferences: ^0.5.6+3
  date_util: ^0.1.4
  searchable_dropdown: ^1.1.3
  flutter_email_sender: ^3.0.1
  image_picker: ^0.6.5
  date_picker_timeline: ^1.2.0
  search_choices: ^1.0.15
  minimize_app: ^0.1.1
  move_to_background: ^1.0.0+1
  syncfusion_flutter_charts: ^18.1.45
  connectivity: ^0.4.8+2
  csv: ^4.0.3
  mailer2: ^1.2.5
  basic_utils: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
